# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [11]:
import numpy as np
arr=np.random.randint(1,21,size=(5,5))
print(arr)
arr[0:5,2]=1
print()
print(arr)


[[ 2 15 11  8  2]
 [20  9 13  7 13]
 [20  9  6 16 18]
 [ 5  8 14  9 19]
 [16 13 18  1 20]]

[[ 2 15  1  8  2]
 [20  9  1  7 13]
 [20  9  1 16 18]
 [ 5  8  1  9 19]
 [16 13  1  1 20]]


In [25]:
a2=np.random.randint(1,16,size=(4,4))
print(a2)
print()

np.fill_diagonal(a2,5)
print(a2)

[[ 5  3  7  9]
 [ 5  2  8  9]
 [ 7 14  5 14]
 [ 3  8 14 15]]

[[ 5  3  7  9]
 [ 5  5  8  9]
 [ 7 14  5 14]
 [ 3  8 14  5]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [27]:
a3=np.arange(1,37).reshape(6,6)
print(a3)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [44]:
a4=np.random.randint(1,20,size=(5,5))
print(a4)
print()

border=np.concatenate((a4[0,:],a4[-1,:],a4[:,0],a4[:,4]))
print(border)

[[16 16 12  6 15]
 [14  7 11  4  1]
 [19  5  7  9 12]
 [ 3 10  2 16 11]
 [18  2  8  3 10]]

[16 16 12  6 15 18  2  8  3 10 16 14 19  3 18 15  1 12 11 10]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [48]:
a5=np.random.randint(1,25,size=(3,4))
print(a5)
print()
a6=np.random.randint(1,25,size=(3,4))
print(a6)


[[18 20 22 20]
 [22 19  3 19]
 [18 13 18  7]]

[[15  8 13  9]
 [12 12  7  2]
 [22  1 14 13]]


In [53]:
a7=np.random.randint(1,25,size=(4,4))
print(a7)
print()
a8=np.random.randint(1,25,size=(4,4))
print(a8)
row_sum=np.sum(a7,axis=1)
column_sum=np.sum(a8,axis=0)
print()
print(row_sum)
print(column_sum)

[[ 2  7  2 20]
 [ 4 21 18  5]
 [19 22 17 23]
 [ 9 18  1  4]]

[[ 3  9  1 21]
 [ 3  9 14  9]
 [10 15  3  9]
 [11 21 16 16]]

[31 48 81 32]
[27 54 34 55]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [56]:
a9=np.random.randint(1,25,size=(5,5))
print(a9)

print("median",np.median(a9))
print("mean",np.mean(a9))
print("standard deviation",np.std(a9))
print("variance",np.var(a9))

[[10  3 18 23 24]
 [22  1 20  9  2]
 [ 2 15 22  2  1]
 [ 8 12 20  8  7]
 [24 23  4 12 14]]
median 12.0
mean 12.24
standard deviation 8.154900367263846
variance 66.5024


In [76]:
a10=np.arange(1,10).reshape(3,3)
print(a10)

mean = np.mean(a9)
std_dev = np.std(a9)
normalized_array = (a9 -mean)/std_dev

print("Normalized array:")
print(normalized_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-0.27468147 -1.13306105  0.70632377  1.31945205  1.4420777 ]
 [ 1.19682639 -1.37831236  0.95157508 -0.39730712 -1.25568671]
 [-1.25568671  0.33844681  1.19682639 -1.25568671 -1.37831236]
 [-0.51993278 -0.02943016  0.95157508 -0.51993278 -0.64255843]
 [ 1.4420777   1.31945205 -1.0104354  -0.02943016  0.21582115]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [77]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[6 3 3]
 [9 5 3]
 [5 4 5]]
1D array:
[ 9  2 10]
Resulting array:
[[15  5 13]
 [18  7 13]
 [14  6 15]]


In [91]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 6  9  6  9]
 [ 7  6  4  4]
 [ 1  3 10  6]
 [10  4 10  1]]
1D array:
[8 3 7 8]
Resulting array:
[[-2  1 -2  1]
 [ 4  3  1  1]
 [-6 -4  3 -1]
 [ 2 -4  2 -7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [96]:
a14=np.random.randint(1,11,size=(3,3))
print(a14)
print()
determinant=np.linalg.det(a14)
invers=np.linalg.inv(a9)
eigenval=np.linalg.eigvals(a9)
print()
print(determinant)
print()
print(invers)
print()
print(eigenval)

[[4 1 6]
 [8 2 3]
 [3 6 4]]


189.00000000000003

[[ -0.58382066  -0.29727096  -1.74756335   2.79044834  -0.22709552]
 [  0.52211726   0.28639976   1.64582396  -2.61778378   0.25536062]
 [ -0.46581197  -0.26068376  -1.4017094    2.31623932  -0.22222222]
 [  2.89413705   1.680012     8.70880192 -14.11081122   1.23196881]
 [ -2.20452842  -1.32643575  -6.77222972  10.95021742  -0.95126706]]

[ 58.59445445 +0.j         -12.2013111 +14.72284277j
 -12.2013111 -14.72284277j  20.86783557 +0.j
  -0.05966781 +0.j        ]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [100]:
a15=np.arange(1,10).reshape(3,3)
# Reshape the array to shape (1, 9)
reshaped_array_1 = a15.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [101]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[16 11  2  1 15]
 [18 12 14  1  9]
 [ 9 13  4 13  1]
 [13 14 15  2 12]
 [16  8 20 16  7]]
Flattened array:
[16 11  2  1 15 18 12 14  1  9  9 13  4 13  1 13 14 15  2 12 16  8 20 16
  7]
Reshaped array:
[[16 11  2  1 15]
 [18 12 14  1  9]
 [ 9 13  4 13  1]
 [13 14 15  2 12]
 [16  8 20 16  7]]


In [103]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner elements:")
print(corners)

Original array:
[[ 7 15 12  1 10]
 [10  3  3 20 17]
 [ 2 11 18  1  3]
 [17  6 15  3 13]
 [10 17  9  5  6]]
Corner elements:
[ 7 10 10  6]


In [104]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[13  2  1 14]
 [ 1  2  9  1]
 [18 13 13 15]
 [ 7 20  5  6]]
Modified array:
[[10  2  1 10]
 [ 1  2  9  1]
 [10 10 10 10]
 [ 7 10  5  6]]


In [105]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [106]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [107]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 2 12  8  3]
 [ 6 20 18 11]
 [ 4 20 20  5]
 [11  5 11  1]]
Masked array:
[[2 -- 8 3]
 [6 -- -- --]
 [4 -- -- 5]
 [-- 5 -- 1]]
Sum of unmasked elements: 34


In [108]:


# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[14  3  7]
 [18  8 16]
 [ 9 18 19]]
Masked array:
[[-- 3 7]
 [18 -- 16]
 [9 18 --]]
Modified masked array:
[[11  3  7]
 [18 11 16]
 [ 9 18 11]]
