In [3]:
import numpy as np
a1=np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
a2=np.array([1,2,3,4,5])
a2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
a2=np.array([[1,3,4,5],[1,2,3,4]])
print(a2)
print(a2.shape)

[[1 3 4 5]
 [1 2 3 4]]
(2, 4)


In [11]:
import numpy as np

np.arange(0, 10, 2).reshape(5, 1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix ##
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
print(a1)
print(a1.shape)
print(a1.size)
print(a1.dtype)
print(a1.itemsize)

[1 2 3 4 5]
(5,)
5
int32
4


In [20]:
## numpy vectorize operations ##
a1 = np.array([1,2,3,4])
a2=np.array([10,20,30,40])
print("addition",a1+a2)
print("sub",a1-a2)
print("mul",a1*a2)

addition [11 22 33 44]
sub [ -9 -18 -27 -36]
mul [ 10  40  90 160]


In [21]:
## universal function ##
a3=np.array([2,3,4,5])
print(np.sqrt(a3))
print(np.exp(a3))

[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]


In [23]:
##array slicing ##
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:

a1[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [44]:
#modify elements##
a1[0,0]=100
a1

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [45]:
a1[1:]=50
a1

array([[100,   2,   3,   4],
       [ 50,  50,  50,  50],
       [ 50,  50,  50,  50]])

In [46]:
data=np.array([1,2,3,4,5])
print(np.mean(data))
print(np.std(data))

3.0
1.4142135623730951


In [51]:
a4=np.array([1,2,3,4,5])
a4[(a4>=2)& (a4<=5)]


array([2, 3, 4, 5])